/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OpenAI-compatible chat completions
         * @description Accepts requests in OpenAI Chat Completions format. The `model`
         *     field can be either:
         *
         *     * **An alias** (`smart`, `fast`, …) — resolved through the
         *       gateway's `model_aliases` config, with the alias's fallback
         *       chain applied on primary failure.
         *     * **A direct `<provider>/<model>` form** (`anthropic-prod/claude-opus-4-7`,
         *       `openai-prod/gpt-4o`, `ollama-local/qwen3.5:9b`) — dispatched
         *       directly to that provider with **no fallback chain**. Per
         *       ADR 0011: the transparency principle requires users / admins
         *       to be able to pick a specific model without alias indirection.
         *
         *     The gateway:
         *     - Resolves the model field (alias chain OR direct passthrough)
         *     - Determines the routed inference tier (B4)
         *     - Refuses if below the request's minimum_inference_tier (D1; B4 only annotates)
         *     - Applies anonymization (if enabled, M2)
         *     - Routes to the appropriate provider
         *     - On a fallback-eligible primary failure (alias mode only),
         *       walks the fallback chain
         *     - Tracks cost and telemetry
         *
         *     Tier-floor enforcement (D1) applies to BOTH dispatch modes —
         *     a direct selection of a tier-1 model against a skill that
         *     declares `minimum_inference_tier: 3` is refused with 403.
         *
         *     Per PRD §4.4, the routed Inference Tier is surfaced two ways
         *     on the response:
         *       1. The `routed_inference_tier` field in the JSON body (or in
         *          every streaming chunk's envelope for `stream: true`).
         *       2. The `X-LQ-AI-Routed-Inference-Tier` header (1-5), so
         *          header-only consumers (proxies, instrumentation) don't
         *          need to parse the body.
         *     The provider name is mirrored at `routed_provider` (body) and
         *     `X-LQ-AI-Routed-Provider` (header).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatCompletionRequest"];
                };
            };
            responses: {
                /** @description Completion (or stream) */
                200: {
                    headers: {
                        /**
                         * @description The Inference Tier (1-5) that this request was routed at,
                         *     derived per PRD §1.5.2 / §3.13. Mirrors the
                         *     `routed_inference_tier` field in the response body.
                         */
                        "X-LQ-AI-Routed-Inference-Tier": 1 | 2 | 3 | 4 | 5;
                        /**
                         * @description The configured provider name that handled the request.
                         *     Mirrors `routed_provider` in the response body.
                         */
                        "X-LQ-AI-Routed-Provider": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatCompletionResponse"];
                        "text/event-stream": string;
                    };
                };
                /** @description Invalid request (bad JSON, schema violation, or invalid_model) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
                /** @description Refused — inference tier below request minimum, or provider not allowed (D1) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
                /** @description Upstream provider error (auth, 4xx, or 5xx after fallback) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
                /** @description No adapter available (provider credential not configured) or network error */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available models — aliases + live-discovered provider-native names (D0)
         * @description Returns the OpenAI-compatible ``{object: "list", data: [...]}``
         *     envelope. Each entry carries the standard
         *     ``{id, object, created, owned_by}`` fields plus LQ.AI extensions
         *     documented under ``ModelEntry`` below.
         *
         *     D0 augments the A3 alias-only payload with two live-discovery
         *     sources:
         *
         *     - **Ollama tags** — ``GET <ollama_url>/api/tags`` is called for
         *       every enabled ``ollama`` provider. Each pulled model surfaces
         *       as one entry with ``id = "<provider_name>/<tag>"`` and
         *       ``lq_ai_kind = "provider_native"``. Cached 60 seconds.
         *     - **Anthropic catalog** — ``GET <anthropic_url>/v1/models`` is
         *       called for every enabled ``anthropic`` provider whose API key
         *       env var is populated. Each catalog entry surfaces as one row
         *       with ``id = "<provider_name>/<model_id>"``. Cached 5 minutes.
         *
         *     Per-source failures (Ollama not running, Anthropic key invalid,
         *     network blip) are best-effort: a WARNING is logged and the
         *     source returns no rows; the response still surfaces whatever
         *     other sources produced. The endpoint never raises.
         *
         *     The raw ``provider/model`` form returned by discovery can be
         *     sent verbatim as the ``model`` field on
         *     ``POST /v1/chat/completions`` — D0 also lands the router-side
         *     passthrough that resolves the form directly.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of aliases + discovered models */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            object: "list";
                            data: components["schemas"]["ModelEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OpenAI-compatible embeddings
         * @description Computes vector embeddings for one or more strings against the
         *     embedding model resolved from `model`. `model` may be either a
         *     configured alias (e.g., `embedding`) or a provider-native model
         *     name (e.g., `text-embedding-3-small`); the router resolves
         *     either using the same alias chain as `/v1/chat/completions`.
         *
         *     The response carries the standard OpenAI shape plus the LQ.AI
         *     extensions `routed_inference_tier` and `routed_provider`. The
         *     same tier annotation is also delivered in the
         *     `X-LQ-AI-Routed-Inference-Tier` response header. One row is
         *     written to `inference_routing_log` per call (success or
         *     failure) so the audit log captures embedding workload alongside
         *     chat completions.
         *
         *     Anthropic does not provide an embeddings endpoint; an
         *     Anthropic-routed alias triggers the gateway's fallback walk
         *     until a provider that supports embeddings (typically OpenAI
         *     per ADR 0008) is found.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Alias or provider-native model name */
                        model: string;
                        /** @description Either a single string or an array of strings */
                        input: string | string[];
                        /**
                         * @description Default float; base64 is bandwidth-optimization.
                         * @enum {string}
                         */
                        encoding_format?: "float" | "base64";
                        /**
                         * @description Optional reduced output dimension for OpenAI's
                         *     text-embedding-3-* models. The KB indexing path
                         *     in api/ omits this and uses the model's native
                         *     dim (1536 for text-embedding-3-small/-large).
                         */
                        dimensions?: number;
                        /** @description Optional end-user identifier (passed through to providers that accept it). */
                        user?: string;
                    };
                };
            };
            responses: {
                /** @description Embeddings */
                200: {
                    headers: {
                        /** @description Same value as the response body's `routed_inference_tier`. */
                        "X-LQ-AI-Routed-Inference-Tier"?: 1 | 2 | 3 | 4 | 5;
                        /** @description The provider name that produced the embeddings. */
                        "X-LQ-AI-Routed-Provider"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            object?: "list";
                            data: {
                                /** @enum {string} */
                                object?: "embedding";
                                /** @description Floats; length matches the model's embedding dimension (1536 for text-embedding-3-small). */
                                embedding: number[];
                                index: number;
                            }[];
                            model: string;
                            usage: {
                                prompt_tokens?: number;
                                total_tokens?: number;
                            };
                            /**
                             * @description Derived tier per PRD §1.5.2; same as the X-LQ-AI-Routed-Inference-Tier header.
                             * @enum {integer}
                             */
                            routed_inference_tier?: 1 | 2 | 3 | 4 | 5;
                            /** @description Provider name that handled the request (post-fallback). */
                            routed_provider?: string;
                        };
                    };
                };
                /** @description Invalid model or malformed request body. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
                /** @description Gateway-key auth failed (operator misconfiguration). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
                /** @description Upstream provider rate-limited the call. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
                /** @description Upstream provider error after fallback exhausted. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
                /** @description No adapter available for any provider that supports embeddings. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 as soon as the process is serving requests. Independent of
         *     downstream provider reachability or gateway.yaml validity. Used by
         *     docker-compose / Kubernetes liveness probes.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "alive";
                            service: string;
                            version?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 once gateway.yaml has loaded and validated. Returns 503
         *     otherwise. Used to decide whether to route traffic.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ready";
                            /** @description configured provider count */
                            providers?: number;
                            /** @description model alias count */
                            aliases?: number;
                        };
                    };
                };
                /** @description Not ready (config not loaded or invalid) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inference/current-tier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve the routed inference tier for a (provider, model)
         * @description Returns the derived tier (1-5) that a request would receive given the
         *     operator's gateway.yaml. The backend calls this to populate the tier
         *     badge in the chat UI per PRD §3.13. Unimplemented in M1 (lands in B4).
         */
        get: {
            parameters: {
                query: {
                    provider: string;
                    model: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tier resolved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {integer} */
                            routed_inference_tier: 1 | 2 | 3 | 4 | 5;
                            provider: string;
                            model: string;
                            /** @description human-readable rationale */
                            explanation?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/providers/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-provider health */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Provider statuses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderStatus"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-key, per-model usage and cost */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    group_by?: "provider" | "model" | "tier" | "user" | "project";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usage summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_cost?: number;
                            total_tokens_in?: number;
                            total_tokens_out?: number;
                            groups?: {
                                key?: string;
                                cost?: number;
                                tokens_in?: number;
                                tokens_out?: number;
                                request_count?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/tier-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current Inference Tier configuration
         * @description Returns the loaded tier_policy block from gateway.yaml — defaults,
         *     allowed tiers globally and per-group, warn / refuse settings.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tier configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InferenceTierConfig"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Partial update to tier configuration
         * @description Admin-only. Audited. Updates take effect for new requests immediately.
         *     Partial-update semantics — fields omitted from the request body are
         *     left unchanged.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InferenceTierConfig"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InferenceTierConfig"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/v1/anonymization-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current anonymization configuration (M2)
         * @description Returns the loaded anonymization block from gateway.yaml — `enabled`,
         *     `apply_at_tiers`, and the pass-through keys (`entity_types`, etc.).
         *     The M2 anonymization middleware shipped and runs (pre/post
         *     pseudonymization wired in gateway/app/main.py; PRD §4.7), so this read
         *     surface reflects the live config. See docs/HONEST-STATE.md §3.2.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Anonymization configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            anonymization?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Partial update to anonymization configuration (M2)
         * @description Status: the PATCH (write) surface is NOT yet in code — only the GET
         *     (read) surface is live in gateway/app/api/admin.py. The write path
         *     lands with the anonymization admin UI.
         *     Admin-only. Audited. Updates take effect for new requests immediately.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/v1/config/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload gateway.yaml without restarting the service
         * @description M1 status: NOT yet in code as an HTTP endpoint — this POST route
         *     does not exist in gateway/app/api/admin.py at M1. Hot-reload is
         *     operational at M1 via SIGHUP (gateway/app/config_holder.py +
         *     gateway/app/config_loader.py; see docs/adr/0010-gateway-config-hot-reload.md).
         *     The explicit HTTP reload trigger lands in M2 alongside the alias
         *     write-through mutation endpoints or as a standalone DE.
         *     Admin-only. Re-reads the config file from disk and atomically swaps
         *     in the new state. If the new config is invalid, the call fails with
         *     400 and the existing config is preserved.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reloaded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            providers?: number;
                            aliases?: number;
                            /** Format: date-time */
                            reloaded_at?: string;
                        };
                    };
                };
                /** @description New config invalid; existing config preserved */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the live gateway config (sanitized)
         * @description Returns the live ``GatewayConfig`` snapshot as JSON, with no
         *     secret material (the schema only carries env-var *names*; never
         *     values). Authenticated via ``X-LQ-AI-Gateway-Key``. The web UI
         *     consumes this to populate the provider dropdown when editing
         *     aliases.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Live config payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Missing or invalid X-LQ-AI-Gateway-Key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured model aliases */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alias list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            object: "list";
                            data: components["schemas"]["AliasEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new model alias
         * @description D0.5. Atomic write to gateway.yaml (temp + rename) followed by
         *     in-process hot-reload. 409 if the alias name already exists.
         *     Only the aliased provider is required to be configured; the
         *     gateway validates the payload before writing.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AliasCreateRequest"];
                };
            };
            responses: {
                /** @description Alias created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AliasEntry"];
                    };
                };
                /** @description Alias name already configured */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
                /** @description Invalid payload (bad provider name, etc.) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/aliases/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** Get a single alias */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alias detail (with primary_inference_tier annotation) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AliasEntry"];
                    };
                };
                /** @description Alias not configured */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Remove an alias */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alias removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Alias not configured */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
                /** @description Alias is referenced as a default and cannot be removed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update an existing alias */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AliasUpdateRequest"];
                };
            };
            responses: {
                /** @description Alias updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AliasEntry"];
                    };
                };
                /** @description Alias not configured */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
                /** @description Invalid payload */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GatewayError"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatCompletionRequest: {
            /**
             * @description Model alias (``smart``, ``fast``, …), a raw
             *     ``<provider_name>/<native_model>`` form
             *     (``anthropic-prod/claude-haiku-4-5``) per D0, or a
             *     provider-native model name that any configured provider
             *     lists in its ``models``. Aliases dispatch through the
             *     full alias-resolution + fallback chain; raw forms skip
             *     the alias map and dispatch to a single target.
             */
            model: string;
            messages: {
                /** @enum {string} */
                role: "system" | "user" | "assistant" | "tool";
                content: string;
            }[];
            max_tokens?: number;
            temperature?: number;
            top_p?: number;
            /** @default false */
            stream: boolean;
            /**
             * @description Per-call tier floor. The most restrictive of (this,
             *     `lq_ai_project_minimum_inference_tier`, attached skills'
             *     frontmatter floor) wins; if the routed tier falls below the
             *     effective floor the gateway refuses with HTTP 403 and code
             *     `tier_below_minimum`. Source label in the refusal envelope
             *     is `"request"`.
             * @enum {integer}
             */
            minimum_inference_tier?: 1 | 2 | 3 | 4 | 5;
            /**
             * @description D1: project-level tier floor forwarded by the backend when
             *     the chat lives inside a Project (per
             *     `Project.minimum_inference_tier`). The gateway never queries
             *     the backend for project metadata; the backend is the
             *     authority on chat ↔ project, and this field is the single
             *     carrier on the gateway hop. Source label in refusal envelope
             *     is `"project"`.
             * @enum {integer}
             */
            lq_ai_project_minimum_inference_tier?: 1 | 2 | 3 | 4 | 5;
            /**
             * @description Audit-log routing tag (B3-era). Does NOT by itself trigger
             *     skill prompt assembly — see `lq_ai_skills` for that. When
             *     `lq_ai_skills` is set and `skill_name` is not, the gateway
             *     populates this field with the first attached skill's name
             *     for audit consistency.
             */
            skill_name?: string;
            /**
             * Format: uuid
             * @description For audit log correlation
             */
            chat_id?: string;
            /**
             * @description Apply anonymization layer (M2; ignored before)
             * @default true
             */
            anonymize: boolean;
            /**
             * @description Ordered list of skill names to attach to this request. The
             *     gateway fetches each from the backend's internal-skills
             *     endpoint, assembles the bodies (with reference files and
             *     input substitution applied), and prepends the result to
             *     the system message. Per ADR 0007.
             */
            lq_ai_skills?: string[];
            /**
             * @description Per-skill input bindings, keyed by skill name. Inner dict
             *     maps input variable names to values. Per-skill scoping so
             *     two attached skills with overlapping variable names don't
             *     collide. Required inputs that the skill's frontmatter
             *     declares but the bindings don't provide cause the gateway
             *     to refuse with `code=skill_input_missing` (HTTP 400).
             */
            lq_ai_skill_inputs?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Format: uuid
             * @description UUID of the persisted chat (Task C3). The gateway writes it
             *     into `inference_routing_log.chat_id`. Distinct from the
             *     pre-existing `chat_id` field (B3-era audit-log tag);
             *     `lq_ai_chat_id` takes precedence when both are present and
             *     is the canonical surface after C3.
             */
            lq_ai_chat_id?: string;
            /**
             * Format: uuid
             * @description UUID of the assistant message (Task C3). The backend
             *     generates it before dispatch and forwards it; the gateway
             *     writes it into `inference_routing_log.message_id` so the
             *     audit-log row joins to the persisted message row by `id`.
             */
            lq_ai_message_id?: string;
        };
        ChatCompletionResponse: {
            id: string;
            /** @enum {string} */
            object: "chat.completion";
            /** @description Unix timestamp */
            created: number;
            model: string;
            choices: {
                index?: number;
                message?: {
                    /** @enum {string} */
                    role?: "assistant";
                    content?: string;
                };
                /** @enum {string} */
                finish_reason?: "stop" | "length" | "content_filter" | "tool_calls";
            }[];
            usage?: {
                prompt_tokens?: number;
                completion_tokens?: number;
                total_tokens?: number;
            };
            /** @enum {integer} */
            routed_inference_tier?: 1 | 2 | 3 | 4 | 5;
            routed_provider?: string;
            cost_estimate?: number;
            anonymization_applied?: boolean;
            /**
             * @description Names of skills whose content was successfully assembled
             *     into the prompt for this request (C2 / ADR 0007). Null
             *     when no skills were attached. Backends surface this on
             *     the audit log so operators can see which skills shaped
             *     a given response.
             */
            lq_ai_applied_skills?: string[] | null;
        };
        ModelEntry: {
            /**
             * @description Either a configured alias (``smart``) or a raw
             *     ``<provider_name>/<native_model>`` form
             *     (``anthropic-prod/claude-haiku-4-5``,
             *     ``ollama-local/llama3.1:8b``). The latter form is sendable
             *     verbatim as ``model`` on ``POST /v1/chat/completions``.
             */
            id: string;
            /** @enum {string} */
            object: "model";
            /**
             * @description Always ``0``. The gateway has no provider-relative creation
             *     timestamp; the field is included for OpenAI compatibility.
             */
            created: number;
            /**
             * @description ``"lq-ai-gateway"`` for aliases; the configured provider
             *     name (e.g., ``"ollama-local"``) for provider-native rows.
             */
            owned_by: string;
            /**
             * @description ``"alias"`` for entries from ``model_aliases``;
             *     ``"provider_native"`` for live-discovered Ollama tags or
             *     Anthropic catalog entries.
             * @enum {string}
             */
            lq_ai_kind: "alias" | "provider_native";
            /**
             * @description Tier the request would land at if dispatched at this id.
             *     Present on ``provider_native`` rows; omitted on aliases
             *     (the alias may resolve to different providers via fallback,
             *     so the tier is settled per-request, not per-alias).
             * @enum {integer}
             */
            routed_inference_tier?: 1 | 2 | 3 | 4 | 5;
            /**
             * @description For ``provider_native`` rows: the provider's ``type``
             *     (``anthropic``, ``ollama``, …). Lets clients group rows
             *     under user-friendly section headers.
             * @enum {string}
             */
            provider_type?: "anthropic" | "openai" | "vertex" | "cohere" | "azure_openai" | "bedrock" | "ollama" | "vllm" | "openai_compatible";
        };
        AliasFallback: {
            provider: string;
            model: string;
        };
        AliasEntry: {
            name: string;
            provider: string;
            model: string;
            fallback: components["schemas"]["AliasFallback"][];
            /**
             * @description Derived tier of the primary target. Present on the single-
             *     alias GET; omitted on list responses.
             * @enum {integer}
             */
            primary_inference_tier?: 1 | 2 | 3 | 4 | 5;
        };
        AliasCreateRequest: {
            name: string;
            provider: string;
            model: string;
            fallback?: components["schemas"]["AliasFallback"][];
        };
        AliasUpdateRequest: {
            provider: string;
            model: string;
            fallback?: components["schemas"]["AliasFallback"][];
        };
        GatewayError: {
            error: {
                /**
                 * @description Stable error codes the gateway emits. Tier-policy and
                 *     routing codes (tier_below_minimum, tier_disallowed_globally,
                 *     anonymization_failed) are documented in PRD §1.5.2 / §3.13;
                 *     operational codes are emitted by the request pipeline before
                 *     routing happens.
                 * @enum {string}
                 */
                code: "tier_below_minimum" | "tier_disallowed_globally" | "anonymization_failed" | "invalid_model" | "provider_unavailable" | "rate_limit_exceeded" | "invalid_request" | "not_implemented" | "unauthorized" | "skill_not_found" | "skill_fetch_failed" | "skill_input_missing" | "not_found" | "conflict" | "internal_error";
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        ProviderStatus: {
            name: string;
            /** @enum {string} */
            type?: "anthropic" | "openai" | "vertex" | "cohere" | "azure_openai" | "bedrock" | "ollama" | "vllm" | "openai_compatible";
            healthy: boolean;
            /** Format: date-time */
            last_check_at?: string;
            models?: string[];
            /** @enum {integer} */
            tier?: 1 | 2 | 3 | 4 | 5;
        };
        InferenceTierConfig: {
            providers: {
                name: string;
                /** @enum {string} */
                type: "anthropic" | "openai" | "vertex" | "cohere" | "azure_openai" | "bedrock" | "ollama" | "vllm" | "openai_compatible";
                base_url: string;
                api_key_env: string;
                /** @enum {integer} */
                tier?: 1 | 2 | 3 | 4 | 5;
                models?: string[];
            }[];
            model_aliases: {
                [key: string]: {
                    provider: string;
                    model: string;
                    /** @enum {integer} */
                    tier?: 1 | 2 | 3 | 4 | 5;
                };
            };
            /** @description Override tier on a per-provider/per-model basis if needed */
            tier_assignments: {
                [key: string]: 1 | 2 | 3 | 4 | 5;
            };
            allowed_tiers_global?: (1 | 2 | 3 | 4 | 5)[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
