import type { LauncherConfig } from './config'

/** Minimal KEY=VALUE parser for tests/round-trips (ignores comments + blanks). */
export function parseEnv(text: string): Record<string, string> {
	const out: Record<string, string> = {}
	for (const raw of text.split('\n')) {
		const line = raw.trim()
		if (!line || line.startsWith('#')) continue
		const eq = line.indexOf('=')
		if (eq === -1) continue
		out[line.slice(0, eq)] = line.slice(eq + 1)
	}
	return out
}

/**
 * Render the .env the release compose expects. Keys mirror .env.example.
 * Values are minted secrets/known ports — never user free-text that needs quoting —
 * so a plain KEY=VALUE form is safe. The one user-supplied field, an API key, is a
 * token charset (no spaces/newlines) and is validated upstream in the wizard.
 */
export function renderEnv(cfg: LauncherConfig): string {
	const { secrets: s, ports: p, inference } = cfg
	const anthropic = inference.mode === 'cloud' ? (inference.anthropicApiKey ?? '') : ''
	const openai = inference.mode === 'cloud' ? (inference.openaiApiKey ?? '') : ''
	const ollama = inference.mode === 'ollama' ? inference.baseUrl : 'http://host.docker.internal:11434'

	return [
		'# Generated by Donna for Mac — do not edit by hand.',
		'',
		`DONNA_IMAGE_TAG=${cfg.imageTag}`,
		'',
		'# Host ports',
		`DONNA_WEB_HOST_PORT=${p.donnaWeb}`,
		`API_HOST_PORT=${p.api}`,
		`GATEWAY_HOST_PORT=${p.gateway}`,
		`POSTGRES_HOST_PORT=${p.postgres}`,
		`REDIS_HOST_PORT=${p.redis}`,
		`MINIO_API_HOST_PORT=${p.minioApi}`,
		`MINIO_CONSOLE_HOST_PORT=${p.minioConsole}`,
		'',
		'# adapter-node Origin check — must equal the browser-facing donna-web URL.',
		`ORIGIN=http://localhost:${p.donnaWeb}`,
		'LQ_API_INTERNAL_URL=http://api:8000',
		'',
		'# Required backend secrets',
		'POSTGRES_DB=lq_ai',
		'POSTGRES_USER=lq_ai',
		`POSTGRES_PASSWORD=${s.POSTGRES_PASSWORD}`,
		'MINIO_ROOT_USER=lq_ai',
		`MINIO_ROOT_PASSWORD=${s.MINIO_ROOT_PASSWORD}`,
		'S3_ACCESS_KEY=lq_ai',
		`S3_SECRET_KEY=${s.S3_SECRET_KEY}`,
		`LQ_AI_GATEWAY_KEY=${s.LQ_AI_GATEWAY_KEY}`,
		`JWT_SECRET=${s.JWT_SECRET}`,
		'',
		'# Inference',
		`ANTHROPIC_API_KEY=${anthropic}`,
		`OPENAI_API_KEY=${openai}`,
		`OLLAMA_BASE_URL=${ollama}`,
		''
	].join('\n')
}
