import { test, expect, type Page } from '@playwright/test';
import { execSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const EMAIL = process.env.DONNA_E2E_EMAIL!;
const PASSWORD = process.env.DONNA_E2E_PASSWORD!;

// Plain .txt does NOT ingest on this stack (unsupported_type); use an existing spike PDF
// or generate one via cupsfilter.
function pdfFixture(): string {
  // Prefer an existing spike PDF generated by previous e2es.
  const candidates = ['/tmp/spike-donna.pdf', '/tmp/spike.pdf', '/tmp/spike2.pdf'];
  for (const p of candidates) {
    if (existsSync(p)) return p;
  }
  // Fallback: generate via cupsfilter.
  const p = join(tmpdir(), 'donna-tabular.pdf');
  if (!existsSync(p)) execSync(`cupsfilter /etc/hosts > "${p}" 2>/dev/null`);
  return p;
}

async function login(page: Page) {
  await page.goto('/login');
  await page.fill('input[name="email"]', EMAIL);
  await page.fill('input[name="password"]', PASSWORD);
  await page.click('button:has-text("Sign in")');
  await page.waitForURL('/');
}

test('tabular: upload a doc, add a column, preview, run, see a cell, export', async ({ page }) => {
  test.setTimeout(300_000);
  await login(page);
  await page.goto('/tabular');

  // Switch to the Upload tab.
  await page.getByRole('button', { name: /^Upload$/ }).click();

  // Set the file on the hidden dropzone input.
  await page.getByTestId('dropzone-input').setInputFiles(pdfFixture());

  // Wait for the document to resolve through ingestion → document_id → chip.
  // The picker shows "{n} document(s) selected" once onresolved fires.
  await expect(page.getByText(/document selected/i)).toBeVisible({ timeout: 120_000 });

  // Define one column (the builder starts with one blank column).
  await page.getByPlaceholder('Column name').fill('Governing law');
  await page.getByLabel('Column question').fill("Which state's or country's law governs this document?");

  // Open the cost preview modal.
  await page.getByRole('button', { name: 'Preview cost' }).click();

  // Wait for the modal and confirm the run.
  const dialog = page.getByRole('dialog', { name: /confirm review cost/i });
  await expect(dialog).toBeVisible();
  await dialog.getByRole('button', { name: 'Run review' }).click();

  // The app navigates to /tabular/<uuid> after the execution is created.
  await page.waitForURL(/\/tabular\/[0-9a-f-]+$/i, { timeout: 15_000 });

  // Wait for the grid to appear: the column header and a populated row.
  await expect(page.getByText('Governing law')).toBeVisible({ timeout: 180_000 });
  await expect(page.locator('table tbody tr')).toHaveCount(1, { timeout: 180_000 });

  // Export menu: click the button, verify the Excel link href.
  await page.getByRole('button', { name: /export/i }).click();
  await expect(page.getByRole('link', { name: /excel/i })).toHaveAttribute('href', /export\?format=xlsx/);
});
